name: flutterflow_widgets
description: Widget library for FlutterFlow.
version: 0.0.40
homepage: https://github.com/thruthesky/flutterflow_widgets

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Add links to text
  flutter_linkify: ^5.0.2

  # Get links from text
  linkify: ^4.1.0

  # Open links
  url_launcher: ^6.1.5

  cached_network_image: 3.2.1

  mime_type: 1.0.0
  chewie: 1.3.4

  video_player: 2.4.5
  video_player_android: 2.3.8
  video_player_avfoundation: 2.3.5
  video_player_platform_interface: 5.1.3
  video_player_web: 2.0.12

  path: 1.8.2

  # url preview
  http: ^0.13.5
  html: ^0.15.1

  # md5 for url preview
  crypto: ^3.0.2

  # local storage for url preview
  shared_preferences: ^2.0.15

  # for CustomCalendar with the same version of FF
  table_calendar: 3.0.6
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
